[project]
name = "pyside-widgets"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pyside6>=6.7.2",
    "qtconsole>=5.6.0",
]
